apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  # Because we define this here, it cannot be used in other namespaces
  namespace: app-layer
type: Opaque
data:
  # These are base-64 encoded values, which is not great if we want to 
  # store this in git. There’s no k8s-native way around this, but there 
  # are a number of solutions (such as SealedSecret). But we’ll see how in 
  # Helm we can handle this by putting fake secrets in and then passing 
  # them in at the command line.
  #
  # These are: root, dbpassword1
  db-username: cm9vdA==
  db-password: ZGJwYXNzd29yZDE=